name: eShopOnWeb Build and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: |
         echo $GITHUB_WORKSPACE
         echo --------------------------------
         ls $GITHUB_WORKSPACE
         echo --------------------------------
         dotnet build ./eShopOnWeb.sln --configuration Release
         echo --------------------------------
         echo $GITHUB_WORKSPACE
         ls $GITHUB_WORKSPACE
    - name: Test with dotnet
      run: |
         dotnet test ./eShopOnWeb.sln --configuration Release
         echo --------------------------------
         echo $GITHUB_WORKSPACE
         echo --------------------------------
         ls $GITHUB_WORKSPACE
        
